// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCniVj58zfWFyW5tOcs82Bt5Wq9v9nRVrY',
    appId: '1:594990381370:web:d831f6ebc450e15b73b803',
    messagingSenderId: '594990381370',
    projectId: 'dotted-72221',
    authDomain: 'dotted-72221.firebaseapp.com',
    storageBucket: 'dotted-72221.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzlfc1plMJuBHk7p5ok1JFpQcor7i-ho8',
    appId: '1:594990381370:android:d5d47732701b0d1673b803',
    messagingSenderId: '594990381370',
    projectId: 'dotted-72221',
    storageBucket: 'dotted-72221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcorOdhWdQ_RcHNMJDXdJRzvHEJksMlI',
    appId: '1:594990381370:ios:80655409a024c83a73b803',
    messagingSenderId: '594990381370',
    projectId: 'dotted-72221',
    storageBucket: 'dotted-72221.firebasestorage.app',
    iosClientId: '594990381370-pdinsmu5kpbra1h4lnj0s7kfp4ut06l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dottedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvcorOdhWdQ_RcHNMJDXdJRzvHEJksMlI',
    appId: '1:594990381370:ios:80655409a024c83a73b803',
    messagingSenderId: '594990381370',
    projectId: 'dotted-72221',
    storageBucket: 'dotted-72221.firebasestorage.app',
    iosClientId: '594990381370-pdinsmu5kpbra1h4lnj0s7kfp4ut06l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dottedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCniVj58zfWFyW5tOcs82Bt5Wq9v9nRVrY',
    appId: '1:594990381370:web:0c327ae4cceca9fb73b803',
    messagingSenderId: '594990381370',
    projectId: 'dotted-72221',
    authDomain: 'dotted-72221.firebaseapp.com',
    storageBucket: 'dotted-72221.firebasestorage.app',
  );
}
