name: Build Unsigned iOS IPA for Sideload

on:
  push:
    tags:
      - 'v*'

env:
  IOS_DEPLOYMENT_TARGET: '13.0'

jobs:
  build-ios-unsigned:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .flutter-pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'

      - name: Get dependencies
        run: |
          flutter pub get
          flutter clean
          flutter pub get

      - name: Build unsigned IPA
        run: flutter build ipa --no-codesign --release

      - name: Package .app into IPA (if needed)
        run: |
          # Flutter >=3.10 with --no-codesign often outputs an unsigned .ipa  
          # but if it only gives an .xcarchive, do this:
          if [ ! -f build/ios/ipa/Runner.ipa ]; then
            APP_PATH="build/ios/iphoneos/Runner.app"
            mkdir -p Payload
            cp -r "$APP_PATH" Payload/
            zip -r Runner.ipa Payload
            mv Runner.ipa build/ios/ipa/
          fi

      - name: Find IPA
        id: find_ipa
        run: |
          IPA=$(find build/ios/ipa -name '*.ipa' | head -n1)
          echo "ipa_path=$IPA" >> $GITHUB_OUTPUT

      - name: Create GitHub Release & Upload unsigned IPA
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_ipa.outputs.ipa_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
