name: Build iOS and Upload to GitHub Release

on:
  push:
    tags:
      - 'v*'  # triggers on version tags like v1.0.0

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS release .ipa
        run: flutter build ipa --release

      - name: Find IPA
        id: find_ipa
        run: |
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -n 1)
          echo "ipa_path=$IPA_PATH" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and Upload IPA
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_ipa.outputs.ipa_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
