name: Build iOS and Upload to GitHub Release

on:
  push:
    tags:
      - 'v*'

env:
  IOS_DEPLOYMENT_TARGET: '11.0'

jobs:
  build-ios:
    runs-on: macos-latest
    concurrency:
      group: ios-build-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .flutter-pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/.cocoapods/repos
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'

      - name: flutter pub get
        run: flutter pub get

      - name: flutter clean
        run: flutter clean

      - name: flutter pub get (again)
        run: flutter pub get

      - name: Install CocoaPods
        working-directory: ios
        run: |
          pod repo update
          pod install

      - name: Build iOS IPA
        run: flutter build ipa --release

      - name: Find IPA
        id: find_ipa
        run: |
          echo "ipa_path=$(find build/ios/ipa -name '*.ipa' | head -n1)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release & upload IPA
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_ipa.outputs.ipa_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
